---
database:
  type: ${DB_TYPE}
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  pass: ${DB_PASS}
  cert-path: ${DB_CERT}

daemons:
  watcher:
    enabled: true
    memory-limit: 33554432
    sleep: 5s
    workers:
      - name: import
        enabled: true
  import:
    enabled: true
    memory-limit: 33554432
    sleep: 5s
    params:
      client:
        type: http
        host: ${EXCHANGE_HOST}
        username: ${EXCHANGE_USER}
        password: ${EXCHANGE_PASSWORD}
        user-agent: "Analitics Exchange"
    workers:
      - enabled: true
        memory-limit: 73400320
        name: ProductPrices
        queue: product-price
        sleep: 60s
