---
watcher:
  memory-limit: 33554432
  sleep: 5
  daemons:
    - name: import
      enabled: true
import:
  memory-limit: 33554432
  sleep: 5
  params:
    client:
      host: http://exchange.microk8s.fs.local
      username: analitics_test
      password: analitics_test
  daemons:
    - name: product-price
      sleep: 60
